#!/bin/bash

sudo apt-get -y install gfortran
wget https://github.com/m3g/packmol/archive/refs/tags/v20.14.2.tar.gz
tar -zxf v20.14.2.tar.gz
cd packmol-20.14.2 ; ./configure ; make ; mv packmol ~/packmol
exit 0

